name: json_feed
description: A Dart implementation of JSON Feed v1.1 with freezed/json_serializable codegen.
version: 0.1.0
homepage: https://example.org/json_feed
environment:
  sdk: '>=3.8.0<4.0.0'

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
