name: Dart CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Get dependencies
        run: dart pub get

      - name: Run codegen (build_runner)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: dart test -r expanded
